# Generated by Django 5.1.4 on 2025-04-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archievesystem', '0003_alter_document_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='entity_type',
            field=models.CharField(choices=[('جهة داخلية', 'جهة داخلية'), ('جهة خارجية', 'جهة خارجية')], max_length=20),
        ),
    ]
