# Generated by Django 5.1.4 on 2025-04-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archievesystem', '0005_alter_document_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('وارد', 'وارد'), ('صادر', 'صادر')], max_length=100, verbose_name=' النوع'),
        ),
    ]
