# Generated by Django 5.1.4 on 2025-04-13 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archievesystem', '0006_alter_document_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaldepartment',
            name='external_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archievesystem.externalentity'),
        ),
        migrations.AlterField(
            model_name='internaldepartment',
            name='internal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archievesystem.internalentity'),
        ),
    ]
