# Generated by Django 5.1.6 on 2025-04-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archievesystem', '0008_document_last_modified_by_document_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
